### ISSUE TITLE
Hellblade senua's Sacrifice always capped to 27fps 

### ISSUE THREAD

**Issue by NextWork123** [ChieuNguyen2002/UNISCALER-FSR2-FSR3-FG#2]
Hello,

I'm using Linux (CachyOS), and I've successfully run the other fsr2-fs3 from your repository. However, it has a UI glitch in the game (caused by the frame gen). I wanted to try Uniscaler, which doesn't have glitches, but it runs at 27fps for some reason. You know if is possible to have a fix?

MY GPU: AMD RX 6600

Best Regards,
NextWorks

**Comment by ChieuNguyen2002** [comment]
You can try edit config.toml fsr3 to xess, fake gpu = true, nvapi = true

**Comment by NextWork123** [comment]
> You can try edit config.toml fsr3 to xess, fake gpu = true, nvapi = true

the perfomance are so bad with the other mod i was reaching 80 because frame gen here with xess i reach 23 fps :/ and no glitch but i have so low fps

**Comment by NextWork123** [comment]
> Maybe XeSS not compatible with Frame Generation

yeah much probably seem like isn't frame generating but only upscaling

**Comment by ChieuNguyen2002** [comment]
You can try Lossless Scaling MOD Fake GPU 4090 can made Frame Gen better for you. Turn off Frame Gen in-game, turn on DLSS. Tomorrow I'll upload video tutorial.

**Comment by NextWork123** [comment]
> You can try Lossless Scaling MOD Fake GPU 4090 can made Frame Gen better for you. Turn off Frame Gen in-game, turn on DLSS. Tomorrow I'll upload video tutorial.

unlucky, i can't do on linux the lossless scaling it doesn't run
